language: minimal

services:
- docker

script:
- sudo make dist

before_deploy:
  - cd dist && sudo ../ci/hashgen.sh && cd ..

deploy:
  provider: releases
  api_key:
    secure: EKxPqr/RaQ/4btWLes39wCKeShaiFotS7Eqb9lHTck71KlePUK5nTTUkjT5dzhTdTAJ0dO8XbzVR4w1nTcspgQfNExhkFuU2QuycxO5JeqKIdP1RG4YFPteHln0w/D/4HyVx3hbEkFmdE0xk1YvhBj10dNFEEQ6bBwpRdA+UbeHB/PSiPdpPEVV4o+lsETLWqENX9rFuzGbbxKGOygeZ8rgu24xiuWgujxvTkP/6FV0XSeYrnw97t54xveT9EUdlFm87AAQ+EX0HDfmOmNtx8s0i1nMpKLVaEFNliLpUKaOuv0RAbbpD+PdyWesBYxdgKuC2GsZpauwSu+d5nKfcnGVnn8qeeu+L9icOnFUFdzbLXZfYo/4seKPzt/I8eAJXrcgN/bZHSc1QeLtGT181CjmYUH020v9Ut9z1abI7fcxM+2ae5PeLfanO+ShiIMvVSWfQtug5IQCeOgZPrgfM0cJNvEO8waHWpC7MDZofj3nCqxJrw6J4fu675e9QnGmL1KI/7TbQRkCYVZWD5bBCdVi6qtlCbcexagMxYSdc/S75FF8gmC+9rPWgchswECgVCk8jKzFReLLRhz/A4tsxTT6huccK3qZ+T4tgQ7tnDhkBJUfKemEIgWsvR8DbQtGj4JqQzZY5nCphf9yrCsAq/0+mmp3JB5vPK/Nrf/kGy28=
  file_glob: true
  file: 
    - dist/*.zip
    - dist/*.zip.sha256
  skip_cleanup: true
  on:
    tags: true